### ISSUE TITLE
Error in `golem-wasm-rpc` when trying to install `golem-cli`

### ISSUE THREAD

**Issue by tonidy** [golemcloud/wasm-rpc#52]
I tried to install `golem-cli`

`cargo install golem-cli`

Get the following error:

```sh
error: could not compile `golem-wasm-rpc` (lib) due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `golem-cli v0.0.107`, intermediate artifacts can be found at `/var/folders/fs/mjcxy3_s7ls84f603q6gl9fw0000gn/T/cargo-install0o9Iga`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
ERROR Cargo errored! ExitStatus(unix_wait_status(25856))
ERROR Fatal error:
  × For crate golem-cli: subprocess /opt/homebrew/Cellar/rust/1.79.0/bin/cargo
  │ install golem-cli --version 0.0.107 errored with exit status: 101
  ╰─▶ subprocess /opt/homebrew/Cellar/rust/1.79.0/bin/cargo install golem-cli
      --version 0.0.107 errored with exit status: 101
```

Here is the error from rust compiler:

https://gist.github.com/tonidy/e291ce9a83a0fe1854a0828b6c7c6623

**Comment by vigoo** [comment]
Thanks for reporting! This was caused by a new version of https://github.com/golemcloud/golem-wasm-ast was published as a patch release accidentally, which is part of our upgrade to a new version of wasmtime etc, but the rest of our packages are not ready for that yet. I yanked that crate and will republish it with a different version, `cargo install golem-cli` should work now.

**Comment by tonidy** [comment]
Great, it's working now, I can install `golem-cli` 0.0.108. Thank you
